version: "3"
services:
  postgres-db:
    image: postgres-wiki:latest

    container_name: postgres-db
  
    restart: unless-stopped

    volumes:
      - /home/centos/wiki-js-docker/db-setup/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

    ports:
      - "5353:5432"
  
    networks: 
      - wiki-network

  wiki:
    image: my-wiki-js:latest
    depends_on:
      - postgres-db

    networks: 
      - wiki-network

    restart: unless-stopped

    ports:
      - "8080:3000"


networks:
  wiki-network:
    driver: bridge
