version: "3"
services:

  db:
    image: postgres:11-alpine
    container_name: banco
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikipass
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

    networks: 
      - wiki-network

  wiki:
    image: my-wiki-js:latest
    depends_on:
      - db

    networks: 
      - wiki-network
      
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikipass
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:


networks:
  wiki-network:
    driver: bridge
