version: "3"
services:

  db:
    image: gileno-postgres-11
    container_name: db
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

    networks: 
      - wiki-network

  wiki:
    image: my-wiki-js:latest
    depends_on:
      - db

    networks: 
      - wiki-network
      
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikiuser
      DB_PASS: wikipass
      DB_NAME: db
    restart: unless-stopped
    ports:
      - "80:3000"

volumes:
  db-data:


networks:
  wiki-network:
    driver: bridge
